import 'package:flutter/material.dart';

class AppTheme {
  static ThemeData themeData = ThemeData(
      // applyElevationOverlayColor: false,
      // cupertinoOverrideTheme: const CupertinoThemeData(
      //   primaryColor: Colors.blue,
      // ),
      // // extensions:
      // inputDecorationTheme: InputDecorationTheme(
      //   border: OutlineInputBorder(
      //     borderRadius: BorderRadius.circular(8),
      //   ),
      // ),
      // materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
      // pageTransitionsTheme: const PageTransitionsTheme(
      //   builders: <TargetPlatform, PageTransitionsBuilder>{
      //     TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
      //     TargetPlatform.android: CupertinoPageTransitionsBuilder(),
      //   },
      // ),
      // // platform: TargetPlatform.iOS
      // scrollbarTheme: ScrollbarThemeData(
      //   thumbColor: MaterialStateProperty.all<Color>(Colors.blue),
      // ),
      // splashFactory: InkRipple.splashFactory,
      // useMaterial3: true,
      // visualDensity: VisualDensity.adaptivePlatformDensity,
      // brightness: Brightness.light,
      // canvasColor: Colors.white,
      // cardColor: Colors.white,
      // colorScheme: ColorScheme.fromSwatch(
      //   primarySwatch: Colors.blue,
      //   accentColor: Colors.blue,
      //   brightness: Brightness.light,
      // ),
      // colorSchemeSeed: Colors.blue,
      // dialogBackgroundColor: Colors.white,
      // disabledColor: Colors.grey,
      // dividerColor: Colors.grey,
      // focusColor: Colors.blue,
      // highlightColor: Colors.blue,
      // hintColor: Colors.grey,
      // hoverColor: Colors.blue,
      // indicatorColor: Colors.blue,
      // primaryColor: Colors.blue,
      // primaryColorDark: Colors.blue,
      // primaryColorLight: Colors.blue,
      // primarySwatch: Colors.blue,
      // scaffoldBackgroundColor: Colors.white,
      // secondaryHeaderColor: Colors.blue,
      // shadowColor: Colors.grey,
      // splashColor: Colors.blue,
      // unselectedWidgetColor: Colors.grey,
      // fontFamily: 'Roboto',
      // fontFamilyFallback: const <String>['Roboto'],
      // package: 'flutter_origin',
      // iconTheme: const IconThemeData(
      //   color: Colors.blue,
      //   opacity: 1,
      //   size: 24,
      // ),
      // primaryIconTheme: const IconThemeData(
      //   color: Colors.blue,
      //   opacity: 1,
      //   size: 24,
      // ),
      // primaryTextTheme: const TextTheme(bodyLarge: TextStyle(color: Colors.blue)),
      // textTheme: const TextTheme(bodyLarge: TextStyle(color: Colors.blue)),
      // typography: Typography.material2018(),
      // actionIconTheme: ActionIconThemeData(
      //   backButtonIconBuilder: (context) => const Icon(Icons.arrow_back_ios),
      // ),
      // appBarTheme: const AppBarTheme(
      //   backgroundColor: Colors.white,
      //   foregroundColor: Colors.blue,
      //   systemOverlayStyle: SystemUiOverlayStyle(
      //     statusBarColor: Colors.white,
      //     statusBarIconBrightness: Brightness.dark,
      //   ),
      // ),
      // badgeTheme: const BadgeThemeData(),
      // bannerTheme: const MaterialBannerThemeData(),
      // bottomAppBarTheme: const BottomAppBarTheme(),
      // bottomNavigationBarTheme: const BottomNavigationBarThemeData(),
      // bottomSheetTheme: const BottomSheetThemeData(),
      // buttonBarTheme: const ButtonBarThemeData(),
      // buttonTheme: const ButtonThemeData(),
      // cardTheme: const CardTheme(),
      // checkboxTheme: const CheckboxThemeData(),
      // chipTheme: const ChipThemeData(),
      // dataTableTheme: const DataTableThemeData(),
      // datePickerTheme: const DatePickerThemeData(),
      // dialogTheme: const DialogTheme(),
      // dividerTheme: const DividerThemeData(),
      // drawerTheme: const DrawerThemeData(),
      // dropdownMenuTheme: const DropdownMenuThemeData(),
      // elevatedButtonTheme: const ElevatedButtonThemeData(),
      // expansionTileTheme: const ExpansionTileThemeData(),
      // filledButtonTheme: const FilledButtonThemeData(),
      // floatingActionButtonTheme: const FloatingActionButtonThemeData(),
      // iconButtonTheme: const IconButtonThemeData(),
      // listTileTheme: const ListTileThemeData(),
      // menuBarTheme: const MenuBarThemeData(),
      // menuButtonTheme: const MenuButtonThemeData(),
      // menuTheme: const MenuThemeData(),
      // navigationBarTheme: const NavigationBarThemeData(),
      // navigationDrawerTheme: const NavigationDrawerThemeData(),
      // navigationRailTheme: const NavigationRailThemeData(),
      // outlinedButtonTheme: const OutlinedButtonThemeData(),
      // popupMenuTheme: const PopupMenuThemeData(),
      // progressIndicatorTheme: const ProgressIndicatorThemeData(),
      // radioTheme: const RadioThemeData(),
      // searchBarTheme: const SearchBarThemeData(),
      // searchViewTheme: const SearchViewThemeData(),
      // segmentedButtonTheme: const SegmentedButtonThemeData(),
      // sliderTheme: const SliderThemeData(),
      // snackBarTheme: const SnackBarThemeData(),
      // switchTheme: const SwitchThemeData(),
      // tabBarTheme: const TabBarTheme(),
      // textButtonTheme: const TextButtonThemeData(),
      // textSelectionTheme: const TextSelectionThemeData(),
      // timePickerTheme: const TimePickerThemeData(),
      // toggleButtonsTheme: const ToggleButtonsThemeData(),
      // tooltipTheme: const TooltipThemeData(),
      );
}
